{% set name = "perl-module-build" %}
{% set version = "0.4232" %}
{% set sha256 = "67c82ee245d94ba06decfa25572ab75fdcd26a9009094289d8f45bc54041771b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/L/LE/LEONT/Module-Build-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-inc-latest
  run:
    - perl

test:
  imports:
    - Module::Build

about:
  home: https://github.com/Perl-Toolchain-Gang/Module-Build
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  summary: Build and install Perl modules

extra:
  recipe-maintainers:
    - xileF1337
    - conda-forge/perl-packagers
